export enum AnimationVFX {
    FIREBALL = "FIREBALL",
    FIREBALL_AURA = "FIREBALL_AURA",
    SLASH_HEAVY = "SLASH_HEAVY",
    DOUBLE_SLASH = "DOUBLE_SLASH",
    HOLY_STRIKE = "HOLY_STRIKE",
    HEAL_GLOW = "HEAL_GLOW",
    SUMMON_FLASH = "SUMMON_FLASH",
}
