export enum AnimationVFX {
    FIREBALL = 'FIREBALL',
    BRULURE_SACREE = 'BRULURE_SACREE',
    TIR_MORTEL = 'TIR_MORTEL',
    INVOCATION_ARCHER_ATTAQUE = 'INVOCATION_ARCHER_ATTAQUE',
    PLUIE_DE_GEL = 'PLUIE_DE_GEL',
    PLUIE_DE_GEL_FROZEN_HIT = 'PLUIE_DE_GEL_FROZEN_HIT',
    FRACTURE = 'FRACTURE',
    RESONANCE = 'RESONANCE',
    CHATIMENT_LUMINEUX = 'CHATIMENT_LUMINEUX',
    STIGMATES = 'STIGMATES',
    LAMES_JUMELLES = 'LAMES_JUMELLES',
    IMPACT = 'IMPACT',
}
